---
- name: add repo key
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  ignore_errors: True

- name: put repo description
  template: src=docker-debian-8.list dest=/etc/apt/sources.list.d/docker.list
  when: ansible_distribution_major_version == "8"

- name: install docker-engine
  apt: name=docker-engine state=present
