---
- name: install Docker
  yum: name=docker-io state=present
  when: ansible_os_family == 'RedHat'

- name: add Docker key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  when: ansible_distribution == 'Ubuntu'

- name: add Docker repo
  template: src=docker.list dest=/etc/apt/sources.list.d/docker.list
  when: ansible_distribution == 'Ubuntu'
  notify: apt-get update

- meta: flush_handlers

- name: install Docker
  apt: name=lxc-docker state=present
  when: ansible_distribution == 'Ubuntu'

- name: start Docker service
  service: name=docker state=started enabled=yes
  when: ansible_os_family == 'RedHat'

- name: start Docker service
  service: name=docker state=started enabled=yes
  when: ansible_distribution == 'Ubuntu'
