---
- name: add Docker repo
  template: src=docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo

- name: install Docker
  yum: name=docker-ce state=present

- name: create /etc/systemd/system/docker.service.d
  file: state=directory dest=/etc/systemd/system/docker.service.d
  when: docker_insecure_registries | length > 0

- name: put /etc/systemd/system/docker.service.d/docker.conf
  template: src=docker.conf dest=/etc/systemd/system/docker.service.d/docker.conf
  when: docker_insecure_registries | length > 0

- name: start Docker service
  service: name=docker state=started enabled=yes
